- hosts: terraform-ansible
  tasks: 
    - name: Criando o arquivo
      copy:
        dest: /home/admin/index.html
        content: <h1>Feito com terraform e ansible</h1>
    
    - name: Criando o servidor Busybox
      shell: "nohup busybox httpd -f -p 8080 &"