- name: Anexos S3
  hosts: fnbcloud3
  become: yes
  vars:
    bucket_name: files-servicedesk
    directory_name: /home/funarbe-servicedesk/fnbfiles/anexo/
    aws_region: us-east-1
  vars_files:
    - secrets.yml

  tasks:
    - name: Atualizando repositório
      apt:
        update_cache: yes
    
    - name: Instalando o S3FS
      apt:
        name: s3fs
        state: present
    
    - name: Criando arquivo .passwd-s3fs com credenciais da AWS
      copy:
        content: "{{ aws_access_key_id }}:{{ aws_secret_access_key }}"
        dest: /etc/.passwd-s3fs
        owner: root
        group: root
        mode: '0600'
    
    - name: Criar diretório ponto de montagem
      file:
        path: "{{ directory_name }}"
        state: directory
        owner: funarbe-servicedesk
        group: funarbe-servicedesk
        mode: '0777'

    - name: Criar bucket no S3 usando módulo oficial
      amazon.aws.s3_bucket:
        name: "{{ bucket_name }}"
        state: present
        region: "{{ aws_region }}"
      delegate_to: localhost
      vars:
        ansible_python_interpreter: /usr/local/bin/python3.12
    
    - name: Criando arquivo do serviço systemd
      copy:
        content: ""
        dest: /etc/systemd/system/s3fs-fnbservicedesk.service
        owner: root
        group: root
        mode: '0600'
    
    - name: Criar serviço que Inicia o Ponto de Montagem de Forma Automática
      copy:
        dest: /etc/systemd/system/s3fs-fnbservicedesk.service
        owner: root
        group: root
        mode: '0644'
        content: |
          [Unit]
          Description=Mount S3 bucket using s3fs
          Requires=network-online.target
          After=network-online.target

          [Service]
          Type=forking
          ExecStart=/usr/bin/s3fs {{bucket_name}} {{ directory_name }} -o passwd_file=/etc/.passwd-s3fs -o url=https://s3.us-east-1.amazonaws.com -o use_path_request_style -o allow_other
          ExecStop=/usr/bin/fusermount -u {{ directory_name }}
          Restart=on-failure

          [Install]
          WantedBy=multi-user.target
    
    - name: Recarregar systemd
      command: systemctl daemon-reexec
    
    - name: Habilitar Serviço
      systemd: 
        name: s3fs-fnbservicedesk.service
        enabled: yes
    
    - name: Iniciar Serviço
      systemd:
        name: s3fs-fnbservicedesk.service
        state: started