---    
    - name: "Atualizando Repositório"
      apt:
        update_cache: yes

    - name: "Instalando Dependências"
      apt:
        pkg: 
        - mariadb-server
        - python3-pymysql
        state: latest

    - name: "Criando Banco de Dados para Wordpress"
      community.mysql.mysql_db:
        name: '{{ wp_db_name }}'
        state: present
        login_unix_socket: /run/mysqld/mysqld.sock

    - name: Criando usuário com permissões
      community.mysql.mysql_user:
        name: '{{ wp_db_user }}'
        password: '{{ wp_db_pass }}'
        priv: '{{ wp_db_name }}.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER'
        state: present
        login_unix_socket: /run/mysqld/mysqld.sock
        host: '{{ item }}'
      with_items:
      - 'localhost'
      - '127.0.0.1'
      - '{{ wp_ip }}'
    
    - name: Substituindo - Libera permissão remota no mysql
      replace:
        path: /etc/mysql/mariadb.conf.d/50-server.cnf
        regexp: '{{ item.regexp }}'
        replace: '{{ item.replace }}'
      with_items:
      - {regexp: '127.0.0.1', replace: '0.0.0.0'}
      notify: 
        - restart mysql
