---
- hosts: wordpress
  become: yes
  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted
  tasks:
    - name: "Atualizando Repositório"
      apt:
        update_cache: yes
    
    - name: "Instalando Dependências"
      apt:
        pkg: 
        - apache2
        - curl
        - php 
        - php-mysql 
        - php-curl 
        - php-gd 
        - php-mbstring 
        - php-xml 
        - php-xmlrpc 
        - php-soap 
        - php-intl 
        - php-zip 
        - libapache2-mod-php

        state: latest

    #- name: "Baixando Wordpress"
    #  shell: "cd /tmp; curl -O https://wordpress.org/latest.tar.gz; tar -xvzf latest.tar.gz;"

    - name: "Baixando Wordpress"
      unarchive:
        src: https://wordpress.org/latest.tar.gz
        dest: /tmp
        remote_src: yes

    
    - name: "Movendo Wordpress para Diretório do Apache"
      copy:
        src: /tmp/wordpress
        remote_src: yes 
        dest: /var/www/html
    
    - name: "Alterando Dono, Grupo e Permissões"
      file:
        path: /var/www/html/wordpress
        owner: www-data
        group: www-data
        recurse: yes
        #state: directory
        mode: 0755
    
    - name: "Configurando o Apache"
      template:
        src: templates/wordpress.conf.j2
        dest: /etc/apache2/sites-available/wordpress.conf
      notify:
        - restart apache

    - name: Habilitar site WordPress (a2ensite)
      command: a2ensite wordpress.conf
      args:
        creates: /etc/apache2/sites-enabled/wordpress.conf
    
    - name: Desabilitar site Padrão (a2dissite)
      command: a2dissite 000-default.conf
    
    - name: Habilitar Módulo rewrite 
      command: a2enmod rewrite
      args:
        creates: /etc/apache2/mods-enabled/rewrite.load
    
    - name: Reload no modulo do Apache
      service:
        name: apache2
        state: reloaded

    - name: "Criando uma cópia do arquivo de configuração do wordpress"
      copy:
        src: '{{ wp_dir }}/wp-config-sample.php' 
        dest: '{{ wp_dir }}/wp-config.php'
        force: no
        remote_src: yes

    - name: Substituindo credenciais no arquivo de configuração
      replace:
        path: '{{ wp_dir }}/wp-config.php'
        regexp: '{{ item.regexp }}'
        replace: '{{ item.replace }}'
      with_items:
      - {regexp: 'database_name_here', replace: '{{ wp_db_name }}'}
      - {regexp: 'username_here', replace: '{{ wp_db_user }}'}
      - {regexp: 'password_here', replace: '{{ wp_db_pass }}'}
      - {regexp: 'localhost', replace: '{{ wp_db_ip }}'}
    
    - name: "Alterando Dono, Grupo e Permissões"
      file:
        path: /var/www/html/wordpress
        owner: www-data
        group: www-data
        recurse: yes
        #state: directory
        mode: 0755
    
- hosts: mysql
  handlers:
    - name: restart mysql
      service: 
        name: mysql
        state: restarted
  become: yes
  tasks:
    - name: "Atualizando Repositório"
      apt:
        update_cache: yes

    - name: "Instalando Dependências"
      apt:
        pkg: 
        - mariadb-server
        - python3-pymysql
        state: latest

    - name: "Criando Banco de Dados para Wordpress"
      community.mysql.mysql_db:
        name: '{{ wp_db_name }}'
        state: present
        login_unix_socket: /run/mysqld/mysqld.sock

    - name: Criando usuário com permissões
      community.mysql.mysql_user:
        name: '{{ wp_db_user }}'
        password: '{{ wp_db_pass }}'
        priv: '{{ wp_db_name }}.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER'
        state: present
        login_unix_socket: /run/mysqld/mysqld.sock
        host: '{{ item }}'
      with_items:
      - 'localhost'
      - '127.0.0.1'
      - '{{ wp_ip }}'
    
    - name: Substituindo - Libera permissão remota no mysql
      replace:
        path: /etc/mysql/mariadb.conf.d/50-server.cnf
        regexp: '{{ item.regexp }}'
        replace: '{{ item.replace }}'
      with_items:
      - {regexp: '127.0.0.1', replace: '0.0.0.0'}
      notify: 
        - restart mysql
